(node:50160) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, lstat '/projects/adapt_lab/shared/TPOT/bids_data/derivatives/working_bids/fmriprep_wf/single_subject_TPOT083_wf/func_preproc_ses_1_task_affect_acq_2_run_02_wf/bold_confounds_wf/conf_corr_plot/_node.pklz'
    at Object.lstatSync (fs.js:841:3)
    at isDirectory (/usr/lib/node_modules/bids-validator/utils/files/readDir.js:130:23)
    at files.map.file (/usr/lib/node_modules/bids-validator/utils/files/readDir.js:116:9)
    at Array.map (<anonymous>)
    at getFiles (/usr/lib/node_modules/bids-validator/utils/files/readDir.js:99:9)
    at files.map.file (/usr/lib/node_modules/bids-validator/utils/files/readDir.js:117:7)
    at Array.map (<anonymous>)
    at getFiles (/usr/lib/node_modules/bids-validator/utils/files/readDir.js:99:9)
    at files.map.file (/usr/lib/node_modules/bids-validator/utils/files/readDir.js:117:7)
    at Array.map (<anonymous>)
(node:50160) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:50160) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/process.py", line 101, in _python_exit
    thread_wakeup.wakeup()
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/process.py", line 89, in wakeup
    self._writer.send_bytes(b"")
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/connection.py", line 183, in send_bytes
    self._check_closed()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/connection.py", line 136, in _check_closed
    raise OSError("handle is closed")
OSError: handle is closed
